import type { NextPage } from 'next'
import Head from 'next/head'

import { FullScreenContainer } from '../components/DesignSystemElements/FullScreenContainer/index';
import { Header } from '../components/DesignSystemElements/Header/index';
import { Heading } from '../components/DesignSystemElements/Heading/index';
import { FluidContainer } from '../components/DesignSystemElements/FluidContainer/index';

const Home: NextPage = () => {
  return (
    <FullScreenContainer>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <Heading variant="h1">
          App Ideas
        </Heading>
      </Header>
    </FullScreenContainer>
  )
}

export default Home
