import type { NextPage } from 'next'
import Head from 'next/head'

import { FullScreenContainer } from '../components/DesignSystemElements/FullScreenContainer/index';
import { Header } from '../components/DesignSystemElements/Header/index';
import { Heading } from '../components/DesignSystemElements/Heading/index';
import { FluidContainer } from '../components/DesignSystemElements/FluidContainer/index';
import { Flex } from '../components/DesignSystemElements/Flex/index';

const Home: NextPage = () => {

  const percentageGeneral = ((0/88)*100).toFixed(2)
  const percentageBegginer = ((0/35)*100).toFixed(2)
  const percentageIntermediate = ((0/33)*100).toFixed(2)
  const percentageAdvanced = ((0/20)*100).toFixed(2)

  return (
    <FullScreenContainer>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <Heading variant="h1">
        {`App Ideas (${percentageGeneral})%`} 
        </Heading>
      </Header>
      <FluidContainer>
        <Heading variant="h2">
          {`Tier-1: Beginner Projects (${percentageBegginer})%`} 
        </Heading>
      </FluidContainer>
      <FluidContainer>
        <Heading variant="h2">
          {`Tier-2: Intermediate Projects (${percentageIntermediate})%`} 
        </Heading>
      </FluidContainer>
      <FluidContainer>
        <Heading variant="h2">
          {`Tier-3: Advanced Projects (${percentageAdvanced})%`} 
        </Heading>
      </FluidContainer>
    </FullScreenContainer>
  )
}

export default Home
